# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantia_reservada', models.FloatField()),
                ('cotacao', models.FloatField()),
                ('descricao', models.TextField()),
                ('minimo', models.FloatField()),
                ('maximo', models.FloatField()),
                ('metodos', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('endereco', models.CharField(max_length=250)),
                ('saldo', models.FloatField(default=0)),
                ('carteira_xrb', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=250, unique=True)),
                ('status_verificacao', models.CharField(
                    choices=[('NV', 'N\xe3o Verificado'), ('V1', 'Verificado Level 1'), ('V2', 'Verificado Level 2')],
                    default='NV', max_length=200)),
                ('numero_transacoes', models.IntegerField(default=0)),
                ('valor_transacoes', models.FloatField(default=0)),
                ('reputacao', models.FloatField()),
                ('data_entrou', models.DateTimeField()),
                ('data_ultimo_login', models.DateTimeField(default=models.DateTimeField())),
                ('login_email_token', models.CharField(default='Token', max_length=50)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.IntegerField(default=0)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='proprietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comprincipal.Cliente'),
        ),
    ]
