# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comprincipal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_entrou',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_ultimo_login',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='reputacao',
            field=models.FloatField(default=0),
        ),
    ]
